### ISSUE TITLE
Class:Institution

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#146]
|  |  |
| ---- | ---- |
| **Parent** | ObjectGroup |
| **Definition** | The institution that maintains the collection |
| **Repeatable** | Yes |
| **Relationships** | CollectionDescription (1 to many) <-> Institution (0 to 1) |
| **Potential standards/vocabularies/ontologies to adopt** | "AIISO (http://vocab.org/aiiso/), FOAF (http://xmlns.com/foaf/0.1/)" |
| **Notes** |  |

**Comment by rondlg** [comment]
I'm not sure we actually need this as a separate class because we have OrganisationalUnit. 

This would be a record with OrganisationUnitType = Institution. Especially for collections that sit within a multi-institutional hierarchy. For example NMNH is an stitution that sits with Smithsonian which is also an institution. I vote to get rid of this!

**Comment by mtrekels** [comment]
Closed, as institution is covered by organisationalUnit
