### ISSUE TITLE
Property:institutionAlternativeName

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#148]
|  |  |
| ---- | ---- |
| **Definition** | Alternative name for the institution in English, if commonly used and the official name is not in English. |
| **Existing property** | dc:alternative |
| **Existing class** |  |
| **Existing property identifier** | http://purl.org/dc/terms/alternative |
| **Format** | Text |
| **Required** |  |
| **Repeatable** |  |
| **Constraints** |  |
| **Examples** | The Muséum national d'Histoire naturelle is also refered to in English as `National Museum of Natural History,Paris`, `Field Columbian Exposition` |
| **Notes** | This should not just be a translation of a name but should aid disambiguation. It may also be used to list alternative and historical names as values in lieu of creating individual collection description records for them.  |

**Comment by MikeTrizna** [comment]
This definition might be a bit restrictive, since there are other scenarios where an institution might have alternative names. For example, the "Smithsonian National Museum of Natural History" used to be referred to as the "United States National Museum", which is why its acronym is USNM.

**Comment by qgroom** [comment]
It would be useful to have an English version of institution name. Perhaps we should have a property englishName and leave this for other alternative names?

@mswoodburn @debpaul What do you think?

**Comment by dbloom** [comment]
I was thinking something similar. If this field is to contain an English name why not rename to alternativeNameEng or similar? Most generally, why do we need an alternative name to be in English?  What is the purpose of this field if used this way? The "Muséum national d'histoire naturelle" is the name of the museum, I'm not sure that "The French National Museum of Natural History" or "National Museum of Natural History" is really an alternative name as much as it is a translation of the proper name in French.

**Comment by wouteraddink** [comment]
I would say that extensive information about an organisation is not in scope of a collection description standard. Ideally you only need to have an identifier to an entity responsible for access to a collection (hosting it and publishing data about the collecition) for and an entity owning a collection (usually an organisation, and usually host and owner are the same). I can agree that in addition to a GRID or ROR identifier we might allow for a (English) name too (one only), as a human readable (not always unique) identifier and also to cater for describing past collections at institutes that do no longer exist and therefore do not have a GRID identifier. Following GRID and ROR we could add an alternate label property too (instead of property:alternative name), which could be, to follow GRID, multiple labels of type alias, acronym or language, where a language label needs to have a iso639 value to describe the language.  It should be possible to describe the source url of this data: GRID or ROR or CETAF or other.

**Comment by rondlg** [comment]
There are a number of data concepts in here that probably need to be disambiguated. The biggest one (dare I say it) is, is institution as a separate class even required? We have OrganisationalUnit which is quite flexible and this seems to be just a special case of that. If we went that route then to Wouter's point we wouldn't need much more than an identifier to whatever the canonical institutional record was which would have all it's descriptive data.

**Comment by WUlate** [comment]
¿Nombre alternativo solo en inglés?  
Can we use a language property on the alternativeName property? Should this a special format ("text in <language>") ?

To follow @dbloom's example, what about "Museo de Historia Natural de París"?  I've seen that in specimen labels (and therefore in the Collections Catalogue of Collection Management Systems).

Also, Plazi's different acronyms used for the same institution hinted what real data might look like:
 
![image](https://user-images.githubusercontent.com/1085601/80816340-f9c3c980-8b94-11ea-877a-1a4577a776a2.png)

**Comment by rondlg** [comment]
If we deprecate the class itself and move this property to orgainisationUnit that "might" reduce the complexity and duplication?

**Comment by rondlg** [comment]
Name changes are interesting and the model handles those with the Parent and CollectionHistory class.

**Comment by mtrekels** [comment]
Closed, as institution is covered by organisationalUnit
