### ISSUE TITLE
Property:institutionAcronym

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#149]
|  |  |
| ---- | ---- |
| **Definition** | Institutional acronym preferred by the institution. This will not necessarily be unique across global institutions. |
| **Existing property** |  |
| **Existing class** |  |
| **Existing property identifier** |  |
| **Format** | Text |
| **Required** |  |
| **Repeatable** |  |
| **Constraints** |  |
| **Examples** | SMNS |
| **Notes** |  |

**Comment by nielsraes** [comment]
https://www.gbif.org/grscicoll/institution/search
In the case of Naturalis this includes the historic institute acronyms, e.g. L for Leiden herbarium which used to be part of Leiden University https://www.gbif.org/grscicoll/institution/search?q=naturalis%20biodiversity%20center&offset=0

**Comment by ekrimmel** [comment]
If historic institutional acronyms are included, will this be a repeatable property?

**Comment by qgroom** [comment]
@ekrimmel it would be better if some historic information is handled by versioning of the data. It is going to get very complicated otherwise.

**Comment by qgroom** [comment]
> https://www.gbif.org/grscicoll/institution/search
> In the case of Naturalis this includes the historic institute acronyms, e.g. L for Leiden herbarium which used to be part of Leiden University https://www.gbif.org/grscicoll/institution/search?q=naturalis%20biodiversity%20center&offset=0

L is a collection acronym, not an institution acronym? Perhaps both?

**Comment by qgroom** [comment]
If we go the route of historical acronyms then we should use start and end dates on them.

**Comment by ekrimmel** [comment]
@qgroom I agree – It seems like we could figure out a way to make note of historical acronyms (where they exist as truly institutional acronyms vs. collection acronyms) without this property being repeatable. What property for this standard would contain the information typically referred to as a 'collection code'?

**Comment by mswoodburn** [comment]
@ekrimmel 'collection code' should fit into the CollectionIdentifier class, I think

**Comment by wouteraddink** [comment]
I am actually now thinking we might need a distinction between InstitutionAcronym and InstitutionCode, where InstitutionAcronym is the acronym of a current institution, to be used as a short label for an institution in e.g. GUIs where there is not always room to display a full name. No historical version needs to be kept, if an institution changes, both its name and acronym may change. Ideally these acronyms should be given by an authority like CETAF or IH to ensure these are regionally or globally unique. InstitutionCode on the other hand is used by an institution to provide a globally unique identifier for collections or specimens, as part of a 'darwincore triplet'. It should be part of a collection description rather than part of an institution description. Not globally unique and historical versions need to be kept, as they keep being used when a collection moves to a new institute or the institute name changes. In many cases the label for InstitutionCode and InstitutionAcronym may be the same, so this distinction may be confusing to people.

**Comment by mtrekels** [comment]
Closed, as institution is covered by organisationalUnit
