### ISSUE TITLE
Property:institutionType

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#151]
|  |  |
| ---- | ---- |
| **Definition** | Pick-list keyword describing the primary activity or purpose of an organisation or entity that holds or uses collections. |
| **Existing property** |  |
| **Existing class** |  |
| **Existing property identifier** |  |
| **Format** | text |
| **Required** | No |
| **Repeatable** | Yes |
| **Constraints** | controlled vocabulary |
| **Examples** | `Education` `Healthcare` `Company` `Archive` `Nonprofit` `Government` `Facility` `Other`|
| **Notes** | identify institutes by grid.ac or ROR identifiers. Consider TDWG Institution Type LSID Ontology: http://rs.tdwg.org/ontology/voc/InstitutionType |

**Comment by szucsichnikolaus** [comment]
examples: genetic, herbarium, fossils
https://terms.tdwg.org/wiki/Natural_Collections_Description#Institution_Type

?Controlled vocabulary

Format: text

**Comment by ekrimmel** [comment]
This property seems odd at the institution level to me (at least based on the examples provided by @szucsichnikolaus here) since very few institutions are defined by a type more specific than "natural history collection" or "museum." Maybe the examples for this term are more along the lines of "museum, private collection, academic/university collection, botanic garden...?"

**Comment by wouteraddink** [comment]
grid.ac uses the following: 

Education | An educational institution where research takes place. Can grant degrees and includes faculties, departments and schools.
Healthcare | A health related facility where patients are treated. Includes hospitals, medical centres, health centres, treatment center. Includes trusts and healthcare systems. 
Company | Business entity with the aim of gaining profit. | SEE EXAMPLE
Archive | Repository of documents, artifacts, or specimens. Includes libraries and museums that are not part of a university. 
Nonprofit | Organisation that uses its surplus revenue to achieve its goals. Includes charities and other non-government research funding bodies. 
Government | An organisation operated mainly by the government of one or multiple countries/territories. |
Facility | A building or facility dedicated to research of a specific area, usually contains specialised equipment. Includes telescopes, observatories and particle accelerators. 
Other

I think we should follow these since we will identifiy institutes by grid.ac or ror identifiers.
a private collection is not an institution.

**Comment by wouteraddink** [comment]
Musea will in usually be of institution type Archive.

**Comment by rondlg** [comment]
It seems that there are two equally valid concepts here but as the term is repeatable both sets of values can be included. I suggest that this is fine for version 1 and if needs be later on we can split them into seperate terms.

**Comment by magpiedin** [comment]
added "TDWG Institution Type LSID Ontology" used in NCD / GGBN -- http://rs.tdwg.org/ontology/voc/InstitutionType

**Comment by wouteraddink** [comment]
definition in NCD: primary activity or purpose of an organisation or entity that holds or uses collections.
terms in NCD:

Aquarium
Archive
Botanic garden
Conservation
Field station
Government
Historical society
Horticultural institution
Industry
Laboratory
Library
Management
Museum
Nature education center
Non university college
Park
Repository
Research institute
School
Science center
Society
University
Zoo

**Comment by mtrekels** [comment]
Closed, as institution is covered by organisationalUnit
