### ISSUE TITLE
Specify datatypes for each term

### ISSUE THREAD

**Issue by essvee** [tdwg/cd#373]
**Notes from review meeting:** [2022-07-28](https://docs.google.com/document/d/16RCOisUhdl3h9ZmV2tZFHaRxnzdSfKbQKXKEaFKFAdA/edit#bookmark=id.8kbcy0om2g6j)

Define permissable datatypes for each property in the termlist: string, number, integer, object, array, boolean, null.  This is mostly already defined in the [json schema docs](https://github.com/tdwg/cd/tree/master/standard/json-schema), so just need shifting over into a new field in the [termlist](https://github.com/tdwg/cd/blob/master/standard/terms/ltc_standard_terms_draft.csv). Not sure how you'd define something like an array of ltc:class objects, so need to find that out too.

**Comment by essvee** [comment]
Closed by #382

**Comment by ben-norton** [comment]
Here's an extended set if data type definitions that are based on json schema.

Data Type
Definition

enumerated
A list of predefined values

Integer
Numeric values without decimal places that range 32 bits from -2^31 to 2^31.

float
Double-precision floating-point numbers with up to 17 significant digits

boolean
Values that may be represented by a binary data set (true/false, 1/0) and stored as 1 bit. Properties with boolean data types may not be null.

date
A value that contains a date (without time) that conforms to ISO 8601 and follows the format YYYY-MM-DD

datetime
A value that contains a single date and time that conforms to ISO 8601 and follows the format YYYY-MM-DD HH:MM:SS

string
String values may contain letters, numbers, puncutation mark, or symbols (including whitespaces). Text values are also referred to as literals, strings, or varchar. Text values are limited to 255 characters except where explicitly denotted otherwise. Text values may be subject to specific formats (character patterns) or set of valid characters.
