### ISSUE TITLE
Rename CollectionStatusHistory class to ObjectGroupStatusHistory

### ISSUE THREAD

**Issue by mswoodburn** [tdwg/cd#430]
Updates required:

1. term CSVs
2. normative documentation
3. wiki
4. wiki diagrams
5. JSON Schemas and JSON/CSV examples

**Comment by magpiedin** [comment]
following discussion & decision on 13 April ([notes](https://docs.google.com/document/d/16RCOisUhdl3h9ZmV2tZFHaRxnzdSfKbQKXKEaFKFAdA/edit#heading=h.ra4n3ebg1un5)):

Leave 'CollectionStatusHistory' class name as is because it's more "about the collection" (i.e., including collection management/people), not strictly "about the object group"
