### ISSUE TITLE
Check "isDistinctObjects" vs. "distinctObjects"

### ISSUE THREAD

**Issue by jbstatgen** [tdwg/cd#442]
In class `ObjectGroupDescriptionScheme` two names exist for the property regarding distinct objects: `isDistinctObjects` and `distinctObjects`. One of these names needs to be choosen.

On the Github issue and master branch the name seems to be `distinctObjects`.
In the wiki and review branch the name is `isDistinctObjects`.

**Comment by jbstatgen** [comment]
It seems `isDistinctObjects` in the review branch is the upToDate version.
This is based on `isMandatoryTerm` in `SchemeTerm`.

**Comment by essvee** [comment]
The review branch version is correct, see #424 for details. The master branch will be updated to match once we merge in review, and the term-level issues are no longer being updated (we agreed this in a working group meeting at the start of the review process, otherwise we'd spend more time updating things that reviewing them - details in #375)
