### ISSUE TITLE
Property:datasetDOIs

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#61]
|  |  |
| ---- | ---- |
| **Definition** | DOIs for public datasets related to the collection description |
| **Dimension** |  |
| **Existing property** |  |
| **Existing class** |  |
| **Existing property identifier** |  |
| **Format** | List |
| **Required** |  |
| **Repeatable** | Yes |
| **Constraints** | Valid resolvable DOI |
| **Examples** |  |
| **Notes** | Could expand to a class if more information than a DOI would be useful |

**Comment by mswoodburn** [comment]
This may be better as a more generic 'datasetLinks' property (or similar) - and potentially expanded from a property to a class, to be able to hold 'linkType' and 'linkAddress' properties?

**Comment by falkogloeckler** [comment]
I'd also prefer 'identifier' over 'link', because it not necessarily need to include the resolving service (like a full DOI URL starting with https://doi.org , compared to the DOI starting from 10.XYZ).
Without a webbased approach in the identifier scheme I wouldn't call it "link".

Most appropriate might be the approach that DataCite uses:
identifier & identifierType   (see https://schema.datacite.org/meta/kernel-4.3/) 
where identifierType is a controlled list of terms with accepted identifiert type schemes.

**Comment by mswoodburn** [comment]
Sounds good - so maybe break this out into a RelatedDatasetIdentifier class, with datasetIdentifier and datasetIdentifierType properties in alignment with the DataCite terms

**Comment by rondlg** [comment]
An damn good idea!

**Comment by mswoodburn** [comment]
Ok, created a pull request for creating that class and removing this property, and added new issues for the class and its properties.

**Comment by mtrekels** [comment]
merged the branch in commit 6e4147d

OK to close this issue
